/***********************************************************
 CSCI 340 - Assignment 2 - Fall 2019
 
 Progammer: Sairamasubash Muppalaneni
 Z-ID: Z1844762
 Section: 1
 TA: Pragna Bodipudi
 Date Due: Thursday, September 19, 2019
 
 Purpose: The purpose of this computer assignment is to write
 a C++ program that implements two different search algorithms.
 The first search algorithm is the linear search algorithm, and
 the second search algorithm is the binary search algorithm. We
 will be using/testing the linear search algorithm and the binary
 search algorithm on randomly generated integers that are stored
 in multiple vectors.
 ************************************************************/

// Inserting the header file in the source code file so that the source code file has access to everything in the header file.
#include "prog2.h"

// Driver program to test two search algorithms - linear
// search and binary search - on vector of integers.

int main ( )
{
    // Define two empty vectors of ints for given sizes and
    // fill them by random integers for given seed values.
    
    vector < int > A ( ARR_SIZE ), B ( TEST_ARR_SIZE );
    Vectors ( A, B, SEED1, SEED2 );
    
    // Print test (1st) vector before sorting its elements.
    cout << "Random Numbers Before Sorting:\n\n";
    printVector ( A );
    
    // Sort test (1st) vector.
    sortVector ( A );
    
    // Print test (1st) vector after sorting its elements.
    cout << "\nRandom Numbers After Sorting:\n\n";
    printVector ( A );
    
    // Print test values from 2nd vector.
    cout << "\nRandom Numbers Searched:\n\n";
    printVector ( B );
    
    // Search each test value from 2nd vector in 1st vector
    // using linear search algorithm.
    
    cout << "\nLinear Search:\n";
    int counter1 = search ( A, B, linearSearch );
    printStat ( counter1, TEST_ARR_SIZE );
    
    // Search each test value from 2nd vector in 1st vector
    // using binary search algorithm.
    
    cout << "\nBinary Search:\n";
    int counter2 = search ( A, B, binarySearch );
    printStat ( counter2, TEST_ARR_SIZE );
    
    return 0;
}


/* This Vectors() function fills the elements of vectors v1 and v2 with random numbers that are generated by
   two sets of pseudo-random numbers, with the seed values of s1 (for the vector v1) and s2 (for the vector
   v2). The seed value of s1 is defined as SEED1 = 1, and the seed value of s2 is defined as SEED2 = 3. We
   are also using the rand() function and some mathematics to randomly generate the integers with the range
   being 1 (LOW) to 1,000 (HIGH). Finally, to Initialize the random number generator (or the rand() function),
   we need to call the srand() function with the seed values s1 and s2 as its arguments (only once). */
void Vectors(vector <int> &v1, vector <int> &v2, int s1, int s2)
{
    
    srand(s1);
    
    for (int i = 0; i < ARR_SIZE; i++)
    {
        v1[i] = rand() % (HIGH - LOW + 1) + LOW;
    }
    
    srand(s2);
    
    for (int i = 0; i < TEST_ARR_SIZE; i++)
    {
        v2[i] = rand() % (HIGH - LOW + 1) + LOW;
    }
    
}


/* This linearSearch() function is a linear search algorithm, where the variable x is the item that is being
   searched in the vector called v. With help from the find() function in STL, this function simply starts
   searching for the variable x from the beginning of vector v (v.begin()) to the end of vector v (v.end()).
   Once there is a match found, this function stops searching. If the search for variable x is successful,
   this linearSearch() function returns true; otherwise, this linearSearch() function returns false. */
bool linearSearch(const vector <int> &v, int x)
{
    
    // Declaring a local variable called match (using the special word auto) to see if the find() function found a match for x.
    auto match = find(v.begin(), v.end(), x);
    
    if(match != v.end())
    {
        return true;
    }
    else
    {
        return false;
    }
        
}


/* This binarySearch() function is a binary search algorithm, where the variable x is the item that is being
   searched in the vector called v. With help from the binary_search() function in STL, this function simply
   starts searching for the variable x in vector v (by using v.begin() and v.end()). If the search for variable
   x is successful, this binarySearch() function returns true; otherwise, this binarySearch() function returns
   false. */
bool binarySearch(const vector <int> &v, int x)
{
    
    if(binary_search(v.begin(), v.end(), x))
    {
        return true;
    }
    else
    {
        return false;
    }
    
}


/* This search() function is a generic search algorithm. It takes a pointer to the search routine called p(),
   and then it calls p() for every single element of vector v2 that is in vector v1. This function also calculates
   the total number of successful searches from both the linear search algorithm and the binary search algorithm,
   and returns that value (called counter) to the main() function as an argument to the printStat() function (the
   printStat() function prints out the final statistics for the search algorithms). */
int search(const vector <int> &v1, const vector <int> &v2, bool (*p) (const vector <int> &, int))
{
    
    // Here is a local variable called counter which keeps count of the total number of successful searches (and it is returned to the main() function).
    int counter = 0;
    
    for (unsigned i = 0; i < v2.size(); i++)
    {
        if (p(v1, v2[i]))
        {
            counter++;
        }
    }
    
    return counter;
    
}


/* The sortVector() function is a type of sorting algorithm. With help from the sort() function in STL, this
   function sorts the elements of the vector called v in ascending order (this function uses v.begin() and
   v.end() as arguments for the sort() function). */
void sortVector(vector <int> &v)
{
    
    sort(v.begin(), v.end());
    
}


/* This printVector() function prints/displays the contents of the vector called v on the standard output. This
   function prints exactly 16 numbers (NO_ITEMS) on a single line (except maybe the last line). Lastly, this
   function also neatly aligns the sorted integers in vector v, by keeping them to the right of the output and
   by having exactly 4 spaces (ITEM_W) between them. */
void printVector(const vector <int> &v)
{
    
    // Declaring a local variable called count which acts as a counter for the number of elements that are on a single line (in the output).
    int count = 1;
    
    for (unsigned i = 0; i < v.size(); i++)
    {
        cout << right << setw(ITEM_W) << v[i];
        
        if (count % NO_ITEMS == 0)
        {
            cout << endl;
        }
        
        count++;
    }
    
    cout << endl;
    
}


/* This printStat() function prints the percent of successful searches (from both the linear search algorithm
   and the binary search algorithm) on the standard output (formatted to be aligned to the right, and as floating-
   point numbers). The variable called totalSucCnt (which is of type integer) is the total number of successful
   comparisons, and the variable called vectorSz (which is also of type integer) is the size of the test vector. */
void printStat(int totalSucCnt, int vectorSz)
{
    
    cout << fixed;
    cout << setprecision(2);
    cout << showpoint;
    
    float successfulSearches = (float)totalSucCnt * 100 / vectorSz;
    
    cout << "\tPercent of Successful Searches = " << setw(5) << successfulSearches << "%";
    
    cout << endl;
    
}

